"""Generates evidence for the report: persona outcomes (D-Q1) and stability
analysis (E-Q7). Run from backend/:  python scripts/evaluate_scenarios.py
Writes reports/scenario_results.md"""
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from app import policy  # noqa: E402
from app.schemas import ApplicationIn  # noqa: E402

BASE = dict(request_id="scenario-000", age=32, no_of_dependents=1, income_annum=1_800_000,
            loan_amount=4_500_000, loan_term=10, cibil_score=780, residential_assets_value=3_000_000,
            commercial_assets_value=0, luxury_assets_value=1_500_000, bank_asset_value=800_000,
            existing_emi_monthly=0, annual_rate=12.0)

PERSONAS = [
    ("Salaried, strong profile", {}, "APPROVE"),
    ("Thin margin: existing EMIs push FOIR to 63%", {"existing_emi_monthly": 30_000}, "REFER"),
    ("Over-leveraged: FOIR 83%", {"existing_emi_monthly": 60_000}, "DECLINE"),
    ("CIBIL 650, otherwise strong", {"cibil_score": 650}, "REFER"),
    ("CIBIL 580: model approves, policy declines", {"cibil_score": 580}, "DECLINE"),
    ("CIBIL 520, short 2-year loan", {"cibil_score": 520, "loan_term": 2, "loan_amount": 1_500_000}, "DECLINE"),
    ("Age 62: outside age band", {"age": 62, "loan_term": 8}, "DECLINE"),
    ("Very high earner (outside training range)", {"income_annum": 30_000_000, "loan_amount": 6_000_000}, "REFER"),
    ("Small ticket loan ₹2 lakh (outside training range)", {"loan_amount": 200_000, "loan_term": 2}, "REFER"),
    ("No assets declared", {"residential_assets_value": 0, "luxury_assets_value": 0, "bank_asset_value": 0}, None),
    ("Six dependents", {"no_of_dependents": 6}, None),
    ("30-year term requested", {"loan_term": 25, "age": 40}, None),
]


def run(overrides: dict) -> dict:
    return policy.assess(ApplicationIn(**{**BASE, **overrides}))


def main():
    lines = ["# Scenario results", "", "Generated by `scripts/evaluate_scenarios.py`.", "",
             "## Personas (D-Q1 edge cases)", "",
             "| Persona | Expected | Got | P(approve) | FOIR | Flags | Suggested change |",
             "|---|---|---|---|---|---|---|"]
    mismatches = 0
    for name, ov, expected in PERSONAS:
        r = run(ov)
        ok = expected is None or r["decision"] == expected
        mismatches += 0 if ok else 1
        lines.append(f"| {name} | {expected or '—'} | {r['decision']}{'' if ok else ' ⚠'} | "
                     f"{policy.pct(r['approval_probability'])} | {r['foir']:.0%} | "
                     f"{', '.join(r['flags']) or '—'} | {r['counterfactual'].summary} |")

    lines += ["", "## Stability: CIBIL sweeps (E-Q7)", "",
              "Same applicant, only the CIBIL score changes.", "",
              "| CIBIL | Model P(approve) | Final decision |", "|---|---|---|"]
    for s in [540, 545, 549, 550, 551, 555, 595, 599, 600, 601, 695, 699, 700, 701]:
        r = run({"cibil_score": s})
        lines.append(f"| {s} | {policy.pct(r['approval_probability'])} | {r['decision']} |")

    # Perturbation test: nudge income by ±1% on random applicants, count decision flips
    rng = np.random.default_rng(7)
    flips, n = 0, 300
    for _ in range(n):
        ov = {"cibil_score": int(rng.integers(300, 901)), "loan_term": int(rng.choice(range(2, 21, 2))),
              "income_annum": float(rng.integers(3, 99)) * 100_000}
        ov["loan_amount"] = round(ov["income_annum"] * float(rng.uniform(1.5, 4.0)), -3)
        ov["existing_emi_monthly"] = 0
        ov["age"] = int(rng.integers(21, 76 - ov["loan_term"]))
        base_d = run(ov)["decision"]
        for f in (0.99, 1.01):
            if run({**ov, "income_annum": ov["income_annum"] * f})["decision"] != base_d:
                flips += 1
                break
    lines += ["", "## Stability: ±1% income perturbation", "",
              f"Out of {n} random applicants, **{flips}** changed decision when income moved by 1% "
              f"({flips / n:.1%}). Flips happen only at a policy or model threshold, which is expected.", ""]
    out = ROOT / "reports" / "scenario_results.md"
    out.write_text("\n".join(lines))
    print("\n".join(lines))
    print(f"\nPersona mismatches: {mismatches}")


if __name__ == "__main__":
    main()
